// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzVWd4JNZAr4_7kMq-5F0yjA5v8R3-ack',
    appId: '1:174987497334:web:1515105b3ff942a0b4b457',
    messagingSenderId: '174987497334',
    projectId: 'eventmanagement-2a410',
    authDomain: 'eventmanagement-2a410.firebaseapp.com',
    storageBucket: 'eventmanagement-2a410.firebasestorage.app',
    measurementId: 'G-WQ5E85X27E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfmEdcB9zBAzL4Uc7jNxJiMfcNhNHFbzA',
    appId: '1:174987497334:android:4eb6ee83e5b61a84b4b457',
    messagingSenderId: '174987497334',
    projectId: 'eventmanagement-2a410',
    storageBucket: 'eventmanagement-2a410.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzVWd4JNZAr4_7kMq-5F0yjA5v8R3-ack',
    appId: '1:174987497334:web:bab99beac894a774b4b457',
    messagingSenderId: '174987497334',
    projectId: 'eventmanagement-2a410',
    authDomain: 'eventmanagement-2a410.firebaseapp.com',
    storageBucket: 'eventmanagement-2a410.firebasestorage.app',
    measurementId: 'G-JDYFEBQB21',
  );
}
